name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  CLAIMS_IMAGE_NAME: ${{ github.repository }}/claims-service
  CONTRACT_IMAGE_NAME: ${{ github.repository }}/contract-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Claims Service
        id: meta-claims
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.CLAIMS_IMAGE_NAME }}

      - name: Build and push Claims Service
        uses: docker/build-push-action@v5
        with:
          context: ./claims-service
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-claims.outputs.tags }}
          labels: ${{ steps.meta-claims.outputs.labels }}

      - name: Extract metadata for Contract Service
        id: meta-contract
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.CONTRACT_IMAGE_NAME }}

      - name: Build and push Contract Service
        uses: docker/build-push-action@v5
        with:
          context: ./contract-service
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-contract.outputs.tags }}
          labels: ${{ steps.meta-contract.outputs.labels }}
